# Generated by Django 4.1.7 on 2024-03-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hearts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=1)),
                ('gender', models.CharField(default='1', max_length=50)),
                ('chp', models.CharField(default='1', max_length=50)),
                ('rbp', models.CharField(default='1', max_length=50)),
                ('chl', models.CharField(default='1', max_length=50)),
                ('fb', models.CharField(default='1', max_length=50)),
                ('ecg', models.CharField(default='1', max_length=50)),
                ('mhr', models.CharField(default='1', max_length=50)),
                ('ex', models.CharField(default='1', max_length=50)),
                ('olp', models.CharField(default='1', max_length=50)),
                ('sl', models.CharField(default='1', max_length=50)),
                ('nm', models.CharField(default='1', max_length=50)),
                ('ts', models.CharField(default='1', max_length=50)),
            ],
        ),
    ]
